// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaAPI.Data;

#nullable disable

namespace VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240916185159_AddDataToVillaTable")]
    partial class AddDataToVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7685),
                            ImageUrl = "https://mangadex.org/covers/cf7b7869-3d9a-4c4d-bd06-249eba113558/72abee3c-5cde-4a6c-bc34-0ea02a1f5148.png",
                            Introduction = "Boku to GAL ga Fufu ni Narumade",
                            Name = "Boku to GAL ga Fufu ni Narumade",
                            Price = 1000f,
                            Rate = 5f,
                            UpdatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7696)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7698),
                            ImageUrl = "https://mangadex.org/covers/ee96e2b7-9af2-4864-9656-649f4d3b6fec/61f990f0-103a-4967-ac64-01dc9938cb5c.jpg.512.jpg",
                            Introduction = "Otaku ni Yasashii Gal wa Inai!?",
                            Name = "Otaku ni Yasashii Gal wa Inai!?",
                            Price = 1000f,
                            Rate = 5f,
                            UpdatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7698)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7700),
                            ImageUrl = "https://mangadex.org/covers/aa6c76f7-5f5f-46b6-a800-911145f81b9b/426242c4-b281-4f19-bb79-c4e15ab6bb24.jpg.512.jpg",
                            Introduction = "Sono Bisque Doll wa Koi o Suru",
                            Name = "Sono Bisque Doll wa Koi o Suru",
                            Price = 1000f,
                            Rate = 5f,
                            UpdatedDate = new DateTime(2024, 9, 17, 1, 51, 59, 517, DateTimeKind.Local).AddTicks(7700)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
